Algoritmo "CRONOMETRO"
// Disciplina  : [Lógica de Programação e JavaScript]
// Professor   : Jailson Costa dos Santos
// Descrição   : Criando um temporizador utilizando a estrutura PARA
// Autor(a)    : Felipe Manzano
// Data atual  : 09/09/2021
Var
   cont, cont1 : Inteiro


Inicio
   Para cont de 0 ate 59 passo 1 faca
      Para cont1 de 0 ate 59 passo 1 faca
         timer(330)
         Escreval (cont, " : ",cont1)
      FimPara
   FimPara


Fimalgoritmo