Algoritmo "LT5A_QUADRADOSINTEIROS"
// Disciplina  : [Lógica de Programação e JavaScript]
// Professor   : Jailson Costa dos Santos 
// Descrição   : Apresentar os quadrados dos números inteiros de 15 a 200.
// Autor(a)    : Felipe Manzano
// Data atual  : 09/09/2021
Var
contador, quadrado : Inteiro


Inicio
Para contador de 15 ate 200 passo 1 faca
quadrado<- contador*contador
Escreval ( contador, "² =", quadrado)
FimPara

Fimalgoritmo