Algoritmo "TEMPORIZADOR"
// Disciplina  : [Lógica de Programação e JavaScript]
// Professor   : Jailson Costa dos Santos
// Descrição   : Criando um temporizador utilizando a estrutura PARA
// Autor(a)    : Felipe Manzano
// Data atual  : 09/09/2021
Var
   cont, cont1 : Inteiro


Inicio
   Para cont de 59 ate 0 passo -1 faca
      Para cont1 de 59 ate 0 passo -1 faca
         timer(1000)
         Escreval (cont, " : ",cont1)
      FimPara
   FimPara


Fimalgoritmo